config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "email#index"
  resources :home
  resources :tasks, except: [:show]
  resources :email
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/email_controller.rb
require 'faker'

class EmailController < ApplicationController
  def index
    @emails = Email.all
  end

  def create
    @flash = "Email received"
    mail = Faker::Internet.email
    object = Faker::Lorem.sentence(word_count: 3)
    body = Faker::Lorem.sentence(word_count: 15)
    read = Faker::Boolean.boolean
    @email_new = Email.new(
      email: mail,
      object: object,
      body: body,
      read: read
    )
    @email_new.save

    respond_to do |format|
      format.html {
        redirect_to root_path
        flash[:notice] = @flash
      }
      format.js {}
    end
  end

  def show
    @email = email_find

    respond_to do |format|
      format.html {
        redirect_to email_path
      }
      format.js {}
    end
  end

  def update
    @email = email_find
    @email.read = params[:read]
    @email.update(email_params)

    respond_to do |format|
      format.html {
        redirect_to root_path
        flash[:notice] = @flash
      }
      format.js { }
    end
  end

  def destroy
    @flash = "Email deleted"
    @email = email_find
    puts "*"*40
    p @email
    p @email.id
    puts "*"*40
    @email.destroy

    respond_to do |format|
      format.html {
        redirect_to root_path
        flash[:notice] = @flash
      }
      format.js { }
    end
  end

  private

  def email_find
    Email.find(params[:id])
  end

  def email_params
    params.permit(:id, :email, :body, :object, :read)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tasks = Task.all
    @categories = Category.all
  end

  private

  def task_params
    params.permit(:title, :deadline, :category)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
before_action :authenticate_user!
  def new
    @categories = Category.all
  end

  def create
    @flash = "Task created"
    @task = Task.new(task_params)
    @category = Category.find(category_params)
    @task.category = @category
    @task.save

    respond_to do |format|
      format.html {
        redirect_to root_path
        flash[:notice] = @flash
      }
      format.js {}
    end
  end

  def edit
    @task = Task.find(params[:id])
    @categories = Category.all
  end

  def update
    @flash = "Task edited"
    @task = Task.find(params[:id])
    @task.status = params[:status]
    @task.update(task_params)

    respond_to do |format|
      format.html {
        redirect_to tasks_path
        flash[:notice] = @flash
      }
      format.js { }
    end
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @flash = "Task deleted"
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html {
        redirect_to root_path
        flash[:notice] = @flash
      }
      format.js { }
    end
  end

  private

  def task_params
    params.permit(:title, :deadline, :description, :status)
  end

  def category_params
    params.require(:Category)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/index.html.erb
<!-- TITLE -->
<h1 class="text-center mb-4">Welcome to my todolist app</h1>

<!-- FORM -->
<%= render 'layouts/task_form'  %>

<!-- TASK LIST -->
<div class="container">
  <ul class="task-list">
    <% @categories.each do  |category|%>
      <li>
        <%= category.title  %>
      </li>
      <div class="card">
        <ul class="card-list">
          <% category.tasks.each do |task|  %>
            <li id="card-item-<%= task.id.to_s %>">
              <!-- Checkbox -->
              <%= check_box_tag "task-" + task.id.to_s, 1, task.status , data: { 
                remote: true, 
                url: task_path(task.id), 
                id: task.id,
                params: { id: task.id, status: task.status}.to_param, 
                method: "put" 
              }, class: 'task-cb' %>
              <span class="card-text">
                <%= task.title  %>
                <% unless task.deadline.nil? %>
                  , to read: <%= task.deadline.strftime('%D')  %>
                <% end %>
              </span>
              <!-- Delete button -->
              <%= link_to "", task_path(task.id), method: :delete, remote: true, class: "fa fa-trash" %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </ul>
</div>

<!-- AVATAR LIST -->
<div class="container">
  <div class="row">
    <% @tasks.each do |task|  %>
      <div class="card col-3">
        <% unless task.image.nil? %>
          <%= image_tag task.image, class: "rounded-circle" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <%= link_to "Sandbox App", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <% unless user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "New task", new_task_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Emails", email_index_path, class: "nav-link" %>
      </li>
      
    </ul>
        <img class="rounded-circle" height="50px" width="50px" src="http://digitalspyuk.cdnds.net/17/25/320x320/square-1498216547-avatar-neytiri.jpg">
  </div>
</nav>

app/views/layouts/_task_form.html.erb
<div class="container">

  <div class="row ml-3">
        <div class="offset-md-3 col-md-6 offset-md-3">
            <%= form_tag(tasks_path, method: "post", class: "form", id: "contact-form", remote: true)  do %>
                <div class="form-group">
                    <%= label_tag "Task", nil, class: "form-label" %>
                    <%= text_field_tag :title, nil, class: "form-control", id: "contact-task", placeholder: "Buy burgers" %>
                </div>
                <div class="form-group">
                    <%= label_tag "Deadline", nil, class: "form-label" %>
                    <%= date_field_tag :deadline, nil, class: "form-control", id: "contact-deadline" %>
                </div>
                <div class="form-group">
                    <%= label_tag "Category", nil, class: "form-label" %>
                    <%= select_tag "Category", options_from_collection_for_select(@categories, "id", "title", "1"), class: "form-control", id: "contact-category"  %>
                </div>
                <div class="text-center">
                    <%= submit_tag("Create task", class: "btn btn-start-order") %>
                </div>
            <%end%>
        </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodolistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" 
          rel="stylesheet" 
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" 
          crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" 
            crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= render 'layouts/flash'  %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_task.html.erb
<li id="card-item-<%= task.id.to_s %>">
    <!-- Checkbox -->
    <%= check_box_tag "task-" + task.id.to_s, 1, task.status , data: { 
        remote: true, 
        url: task_path(task.id), 
        id: task.id,
        params: { id: task.id, status: task.status}.to_param, 
        method: "put" 
        }, class: 'task-cb' %>
    <span class="card-text">
        <%= task.title  %>
        <% unless task.deadline.nil? %>
            , to read: <%= task.deadline.strftime('%D')  %>
        <% end %>
    </span>
    <!-- Delete button -->
    <%= link_to "", task_path(task.id), method: :delete, remote: true, class: "fa fa-trash" %>
</li>

app/views/tasks/_task_list.html.erb
<ul>
  <% @tasks.each do |task|  %>
    <li>
      <%= task.title %>,
      "Deadline : " <%=  task.deadline.strftime("%D")  %>
       <%= link_to "Edit this task", edit_task_path(task) %>
    </li>
  <% end %>
</ul>

app/views/tasks/create.js.erb
document.querySelectorAll(".notice")[0].textContent = "<%= @flash %>";
let categoryId = "<%= @task.category_id %>";
let key = categoryId - 1;
let cardElt = document.querySelectorAll(".card-list")[key];

let cardTaskElt = document.querySelector("#contact-task");
let cardDeadlineElt = document.querySelector("#contact-deadline");
let cardCategoryElt = document.querySelector("#contact-category");

cardElt.insertAdjacentHTML("beforeend", "<%= j render 'task', task: @task %>");

cardTaskElt.value = '';
cardDeadlineElt.value = '';
cardCategoryElt.value = 1;

app/views/tasks/destroy.js.erb
document.querySelectorAll(".notice")[0].textContent = "<%= @flash %>";
let deleteElt = document.querySelector("#card-item-" + <%= @task.id %>);
deleteElt.parentNode.removeChild(deleteElt);

app/views/tasks/edit.html.erb
<h4>Edit your task</h4>
<%= form_tag(task_path, method: "put") do %>
  <div class="form-group">
      <%= label_tag("Your task:") %>
      <%= text_field_tag(:title, @task.title) %>
  </div>

  <div class="form-group">
    <%= label_tag("When is it due for ?") %>
    <%= date_field_tag(:deadline, @task.deadline)  %>
  </div>
    <%= submit_tag("Edit task", class: "btn btn-info") %>
<% end %>
<%= link_to "Delete this task", task_path(@task), method: :delete, class: "btn btn-danger" %>

app/views/tasks/index.html.erb
<% if user_signed_in? %>

  <%= render 'task_list'  %>

<% end %>

<%= link_to "Create a new task", new_task_path, class: "btn btn-info"  %>

app/views/tasks/new.html.erb
<% if user_signed_in? %>
  <%= render 'layouts/task_form'  %>
<% end %>

app/views/tasks/update.js.erb
document.querySelectorAll(".notice")[0].textContent = "<%= @flash %>";